FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=blogginPassword
ENV MYSQL_DATABASE=thedatabase
ENV MYSQL_USER=blogginUser
ENV MYSQL_PASSWORD=blogginPassword

# Exponer el puerto de MySQL
EXPOSE 3306